name: Pull Request Stats

on:
  pull_request:
    types: [ opened ]

permissions:
  pull-requests: write

jobs:
  stats:
    if: github.event.label.name == 'stats-check'
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with: 
          token: ${{ secrets.SECRET_GIT_TOKEN }}
          period: 60
          exclude: sos-core-user